- name: Install docker
  apt:
    name: docker-ce
    state: present

- name: Create docker graph directory
  file:
    path: /mnt/docker
    state: directory

- name: dump
  debug:
    var: hostvars[ansible_host]
    verbosity: 4

- name: Copy unit file
  template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service

- name: Reload systemd daemons
  command: "systemctl daemon-reload"

- name: Start docker service
  service:
    name: docker
    enabled: yes
    state: started